### ISSUE TITLE
Tooltip issue 

### ISSUE THREAD

**Issue by aevi1103** [TanStack/react-charts#341]
Tooltip is not anchored to the chart plot 

![image](https://user-images.githubusercontent.com/22485876/228356933-92ca5fee-dcfa-4e58-b1bc-6e58e21af851.png)

https://codesandbox.io/s/react-charts-sample-9lodo4?file=/src/App.tsx

I forked the demo project, this onw works.

any idea why its not working on a new project?

https://codesandbox.io/s/elastic-ritchie-y4j9ml

![image](https://user-images.githubusercontent.com/22485876/228357349-118d9138-5e6d-4088-a09d-063d5843891b.png)

**Comment by mbogdan0** [comment]
Any updates on this? I have the same issue.

**Comment by benrandja-akram** [comment]
@mbogdan0 npm i @3.0.0-beta.30 seems to fix the issue.

**Comment by paulpopus** [comment]
Experiencing this on `react-charts@3.0.0-beta.54` version as well on line graphs and it looks like the example is also having this problem only on line graphs and not on the bars
[Screencast from 10-04-23 17:02:49.webm](https://user-images.githubusercontent.com/35137243/230880620-c669bb38-c0a1-4ecc-9daf-e6f9090e2d19.webm)

**Comment by bonsmik** [comment]
The problem seems to be with radius of circle on focused element. Occasionally tooltip is in correct position but usual bounding rect size is 0. The reason is that radius of focused element seems to be 0. It is set in this line
 
https://github.com/TanStack/react-charts/blob/de262a7a00efcbd77c49952a45eaf0584af4a5c7/src/seriesTypes/Line.tsx#L105

My guess is that focusedDatum is not always in sync and causes the problem. Not sure how to fix it though

**Comment by bonsmik** [comment]
If focused datum check is removed from radius calculation tooltip will be shown correctly:
`
const radius = showDatumElements === 'onFocus' ? 4 : 2
`

It shouldn't affect elsewhere because it is not shown because of next check

`
const show =
  showDatumElements === 'onFocus'
    ? datum === focusedDatum
    : secondaryAxis.showDatumElements ??
      secondaryAxis.elementType === 'bubble'
`

But I can't say it for sure if there would be some side-effects to make a pull request with given "fix"

**Comment by tannerlinsley** [comment]
This is fixed in the latest release of beta

**Comment by NathanVG** [comment]
I am on `3.0.0-beta.55` and I still have this issue with linecharts. 

<img width="810" alt="image" src="https://github.com/TanStack/react-charts/assets/3620183/f17905c7-eb86-4111-879b-3d38461a0c9a">

**Comment by bardaxx** [comment]
same issue here, anyone knows how to disable the animation of the tooltip?
